# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 翰海尘沙
subtitle: 进击的程序员
description: 技术分享、阅读笔记
author: 翰海尘沙
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://hanhaichensha.coding.me
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: landscape
#theme: leo

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    #github: git@github.com:hanhaichensha/blog.git,gh-pages
    coding: git@git.coding.net:hanhaichensha/blog.git,coding-pages
# 自动备份
backup:
  type: git
  repo: 
    github: git@github.com:hanhaichensha/blogcode.git,master
    coding: git@git.coding.net:hanhaichensha/code.git,master

# 评论
# 1.友言
uyan:
  enable: true
# 2.多说
#duoshuo_shortname: hanhaichensha
# 3.畅言
#changyan:
#  enable: true

# RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 10

# 网站地图
sitemap:
    path: sitemap.xml